<!DOCTYPE html>
<html>
<head>
	<title><?php echo $pageName; ?></title>
	<link href="css/main.css" type="text/css" rel="stylesheet" media="screen" />
</head>
<body>
<div id="header_container">

<div id="header">
	<h1>Opinions Matter!</h1>
    <nav>
		<ul id="nav">
			<li><a href="?action=">Home</a></li>
			<li>|</li>
			<li><a href="?action=">Login</a></li>
		</ul>
	</nav>
</div><!-- /#header -->
</div><!-- /#header_container -->
 
<div id="container">
    <div id="content">